### PR TITLE
Polyamorous module

### LINKED ISSUE #1081: CI against Rails 6-0-stable broken
CI is broken against 6-0-stable since https://github.com/rails/rails/commit/dd46d18e2108f2e953e9811c6eabf5b18fe77ab1.

Needs to be investigated and fixed.

### LINKED ISSUE #1099: Convert Polyamorous into a module
Previously Polyamorous was a [separate gem](https://github.com/activerecord-hackery/polyamorous). It has been moved into the Ransack repo, which is a great step forward. 

However, it is still a gem **_inside_** the Ransack repo. What needs to be done is to convert this code purely into a module. A later refactoring can more closely merge the code, but for now the work needed is:

- Remove the Polyamorous gem-specific code
   - https://github.com/activerecord-hackery/ransack/blob/master/polyamorous/polyamorous.gemspec
  - https://github.com/activerecord-hackery/ransack/blob/master/polyamorous/lib/polyamorous/version.rb
- Add any dependencies needed into the Ransack gemspec
- Move everything under the main `/lib/polyamorous` folder
- Remove the Polyamorous dependency from Ransack
  - https://github.com/activerecord-hackery/ransack/blob/master/ransack.gemspec#L20
- Add the [Polyamorous tests](https://github.com/activerecord-hackery/polyamorous/tree/master/spec) into the Ransack repo and get them to pass

### PR DESCRIPTION
**Pull request by varyonic**
Resumes #1105  Closes #1099  Fixes #1081 ?

### CODE REVIEW

File: spec/ransack/search_spec.rb [hunk 1]
```diff
@@ -271,12 +271,21 @@ module Ransack
...
+          expect(real_query)
+                  .to match(%r{LEFT OUTER JOIN articles ON (\('default_scope' = 'default_scope'\) AND )?articles.person_id = parents_people.id})
+          expect(real_query)
+                  .to match(%r{LEFT OUTER JOIN articles articles_people ON (\('default_scope' = 'default_scope'\) AND )?articles_people.person_id = people.id})
+        else
+          expect(real_query)
+                  .to match(%r{LEFT OUTER JOIN articles ON (\('default_scope' = 'default_scope'\) AND )?articles.person_id = people.id})
+          expect(real_query)
+                  .to match(%r{LEFT OUTER JOIN articles articles_people ON (\('default_scope' = 'default_scope'\) AND )?articles_people.person_id = parents_people.id})
+        end
```
Comment (deivid-rodriguez) [inline spec/ransack/search_spec.rb:287]: If I recall correctly, this is the test that was failing on Rails 6-0-stable. Are you saying that the new query that ransack builds is correct? My understanding was that the CI failure was a real failure that should be fixed.

Comment (seanfcarroll) [reply spec/ransack/search_spec.rb:287]: @deivid-rodriguez @varyonic this does seem to be passing the 6.0 CI, great work.

Comment (nikajukic) [reply spec/ransack/search_spec.rb:287]: I've added an example of a failing test in https://github.com/activerecord-hackery/ransack/issues/1119#issuecomment-630861662
